-- Fix Missing Calendar Tables
-- Use this if the rename migration failed or tables are missing.

DO $$
BEGIN
    -- 1. Create 'calendario_prod' if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'dashboards' AND table_name = 'calendario_prod') THEN
        CREATE TABLE dashboards.calendario_prod (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date DATE NOT NULL,
            type TEXT NOT NULL CHECK (type IN ('feriado', 'meio_dia', 'ponte')),
            description TEXT,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
    END IF;

    -- 2. Create 'calendario_fatur' if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'dashboards' AND table_name = 'calendario_fatur') THEN
        CREATE TABLE dashboards.calendario_fatur (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date DATE NOT NULL,
            type TEXT NOT NULL CHECK (type IN ('feriado', 'meio_dia', 'ponte')),
            description TEXT,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
    END IF;

    -- 3. Cleanup old 'calendario' if it still exists (Optional, preventing confusion)
    -- IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'dashboards' AND table_name = 'calendario') THEN
    --     DROP TABLE dashboards.calendario;
    -- END IF;

    -- 4. Grant Permissions
    GRANT ALL ON dashboards.calendario_prod TO anon, authenticated, service_role;
    GRANT ALL ON dashboards.calendario_fatur TO anon, authenticated, service_role;
    GRANT ALL ON SEQUENCE dashboards.calendario_prod_id_seq TO anon, authenticated, service_role;
    GRANT ALL ON SEQUENCE dashboards.calendario_fatur_id_seq TO anon, authenticated, service_role;

END $$;
