import React from 'react';
import { 
  LayoutDashboard, 
  FileText, 
  CheckCircle2, 
  AlertCircle, 
  Clock, 
  Settings, 
  LogOut, 
  Plus, 
  ChevronRight,
  ChevronLeft, 
  Upload, 
  File as FileIcon, 
  Trash2, 
  Printer,
  Wand2,
  XCircle,
  Menu,
  X,
  Users,
  Shield,
  Camera,
  Search
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Ticket: FileText,
  FileText: FileText,
  Check: CheckCircle2,
  Alert: AlertCircle,
  Clock: Clock,
  Settings: Settings,
  Logout: LogOut,
  Plus: Plus,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  Upload: Upload,
  File: FileIcon,
  Delete: Trash2,
  Print: Printer,
  Magic: Wand2,
  Reject: XCircle,
  Menu: Menu,
  Close: X,
  Users: Users,
  Admin: Shield,
  Camera: Camera,
  Search: Search
};